import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Background,Controls,MiniMap,Handle,Position,ReactFlow} from '@xyflow/react';
import '@xyflow/react/dist/style.css'; import './style.css';
import type {BillingResult,Content,Decision,Subject,TraceStep} from './types/domain';
import {mapDecisionExecution} from './flow/execution/mapDecisionExecution';
const API='http://localhost:8000';
async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(API+path,options);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.detail||b.message||'Request failed')}return r.json()}
function Card({data}:{data:{label:string;status:string;detail?:string}}){return <div className={'node '+data.status}><Handle type="target" position={Position.Left}/><small>{data.status}</small><strong>{data.label}</strong><span>{data.detail||'—'}</span><Handle type="source" position={Position.Right}/></div>}
const nodeTypes={card:Card}; const presets=[['Public Access','anonymous_demo','article_public'],['Meter Remaining','anonymous_demo','article_metered_1'],['Meter Exhausted','anonymous_demo','article_metered_1'],['Premium Subscriber','user_premium','article_premium_1'],['Premium Without Entitlement','user_free','article_premium_1'],['Past-Due Grace','grace_demo','article_premium_1']];
function App(){const [subjects,setSubjects]=useState<Subject[]>([]),[content,setContent]=useState<Content[]>([]),[sid,setSid]=useState('anonymous_demo'),[cid,setCid]=useState('article_metered_1'),[mode,setMode]=useState<'evaluate'|'open'>('open'),[result,setResult]=useState<Decision|null>(null),[billing,setBilling]=useState<BillingResult|null>(null),[replay,setReplay]=useState(0),[error,setError]=useState('');
useEffect(()=>{Promise.all([api<Subject[]>('/api/subjects'),api<Content[]>('/api/content')]).then(([s,c])=>{setSubjects(s);setContent(c)}).catch(e=>setError(e.message))},[]);
const run=async()=>{try{setError('');const key=mode==='open'?`demo-${sid}-${cid}`:undefined;const r=await api<Decision>(`/api/access/${mode}`,{method:'POST',headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:JSON.stringify({subject_id:sid,content_id:cid})});setResult(r);setReplay(0)}catch(e){setError((e as Error).message)}};
const doBilling=async(action:string)=>{try{setBilling(await api<BillingResult>(`/api/demo/billing/${action}`,{method:'POST'}));setResult(null)}catch(e){setError((e as Error).message)}}; const visual=mapDecisionExecution(result);
const detail=(id:string)=>id==='meter'?(result?.meter.bypassed?'bypassed':result?`${result.meter.used}/${result.meter.limit}`:'—'):id==='policy'?(result?.reason_code||'waiting'):id==='decision'?(result?.decision.toUpperCase()||'Decision'):id==='consume'?(result?.consumed?'1 usage':'no usage'):id==='subject'?sid:id==='content'?content.find(x=>x.content_id===cid)?.access_tier:result?.subscription.state;
const nodes=['request','subject','content','subscription','entitlements','meter','policy','decision','consume'].map((id,i)=>({id,type:'card',position:{x:(i%4)*250+30,y:Math.floor(i/4)*170+80},data:{label:id==='entitlements'?'Entitlements':id[0].toUpperCase()+id.slice(1),status:id==='policy'?(result?'matched':'idle'):visual.state(id),detail:detail(id)}})); const links=[['request','subject'],['subject','content'],['content','subscription'],['content','entitlements'],['subscription','meter'],['entitlements','meter'],['meter','policy'],['policy','decision'],['decision','consume']].map(([source,target])=>({id:source+target,source,target,animated:Boolean(result)})); const steps=result?.trace.steps.slice(0,replay||result.trace.steps.length)||[];
return <main><header><div><p className="eyebrow">MONETIZATION SYSTEMS / PDE</p><h1>Paywall Decision Engine</h1><p className="sub">A deterministic explorer for access, entitlement, metering, and billing state.</p></div><div className="health">● SYSTEM READY<br/><small>SQLite · Mock billing · UTC clock</small></div></header><section className="workspace"><aside><h2>Scenario controls</h2><div className="presets">{presets.map(([name,s,c])=><button key={name} onClick={()=>{setSid(s);setCid(c);setResult(null)}}>{name}</button>)}</div><label>Subject<select value={sid} onChange={e=>setSid(e.target.value)}>{subjects.map(s=><option key={s.subject_id} value={s.subject_id}>{s.display_name}</option>)}</select></label><label>Content<select value={cid} onChange={e=>setCid(e.target.value)}>{content.map(c=><option key={c.content_id} value={c.content_id}>{c.title} · {c.access_tier}</option>)}</select></label><div className="seg"><button className={mode==='evaluate'?'on':''} onClick={()=>setMode('evaluate')}>Evaluate</button><button className={mode==='open'?'on':''} onClick={()=>setMode('open')}>Open + consume</button></div><button className="run" onClick={run}>Run real decision →</button><button className="reset" onClick={()=>api('/api/demo/reset',{method:'POST'}).then(()=>{setResult(null);setBilling(null)})}>Reset demo state</button><h2 className="billing-title">Billing actions</h2><div className="billing">{['start-premium','mark-past-due','recover','cancel-at-period-end','expire','send-duplicate'].map(a=><button key={a} onClick={()=>doBilling(a)}>{a}</button>)}</div>{error&&<div className="error">{error}</div>}</aside><div className="canvas"><div className="canvas-head"><span>DECISION CANVAS</span><span className="live">● BACKEND TRACE CONNECTED</span></div><ReactFlow nodes={nodes} edges={links} nodeTypes={nodeTypes} fitView><Background color="#263044" gap={24}/><Controls/><MiniMap/></ReactFlow></div></section><section className="inspector"><div><p className="eyebrow">DECISION INSPECTOR</p>{result?<><h2><span className={'pill '+result.decision}>{result.decision.toUpperCase()}</span> {result.reason_code}</h2><p>{result.explanation}</p></>:<p>Run a backend decision to inspect the authoritative path.</p>}</div><div><b>Meter</b><br/>{result?(result.meter.bypassed?'BYPASSED':`${result.meter.used} / ${result.meter.limit} used · ${result.meter.remaining} remaining`):'—'}</div><div><b>Billing</b><br/>{billing?`${billing.reason} · ${billing.duplicate?'duplicate':'applied'}`:'No event selected'}</div><div><b>Trace / replay</b><br/><button disabled={!result} onClick={()=>setReplay(result?.trace.steps.length||0)}>Replay decision</button>{result&&<div className="timeline">{steps.map((step:TraceStep,i)=><div key={i} className={i<replay||replay===0?'active':''}><code>{step.name}</code>{step.duration_ms?` · ${step.duration_ms} ms`:''}</div>)}</div>}</div></section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
